### ISSUE TITLE
error on startup

### ISSUE THREAD

**Issue by corosuske** [simplificator/sitincator#16]
hi 
cool project, tahnk you so much for sharing it 

i have followed the readme to install this and am running into an issue 
im trying to put our room calendars on this 
i get asked for a calendar-id when i fill this in i get a error 

any idea what might be wrong here ? 

Error while trying to retrieve access token with code <Buffer > { Error: invalid_request
    at Request._callback (/home/pi/Sitincator/resources/app/node_modules/google-auth-library/lib/transporters.js:81:15)
    at Request.self.callback (/home/pi/Sitincator/resources/app/node_modules/google-auth-library/node_modules/request/request.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:194:7)
    at Request.<anonymous> (/home/pi/Sitincator/resources/app/node_modules/google-auth-library/node_modules/request/request.js:1044:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:191:7)
    at IncomingMessage.<anonymous> (/home/pi/Sitincator/resources/app/node_modules/google-auth-library/node_modules/request/request.js:965:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:188:7) code: 400 }
{ Error: invalid_request
    at Request._callback (/home/pi/Sitincator/resources/app/node_modules/google-auth-library/lib/transporters.js:81:15)
    at Request.self.callback (/home/pi/Sitincator/resources/app/node_modules/google-auth-library/node_modules/request/request.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:194:7)
    at Request.<anonymous> (/home/pi/Sitincator/resources/app/node_modules/google-auth-library/node_modules/request/request.js:1044:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:191:7)
    at IncomingMessage.<anonymous> (/home/pi/Sitincator/resources/app/node_modules/google-auth-library/node_modules/request/request.js:965:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:188:7) code: 400 }

**Comment by corosuske** [comment]
trying with a new image seems to have helped with this issue
